services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_lumbung_mesari
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  postgres_test:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_lumbung_mesari_test
    # Map a different host port if you need host access; otherwise omit 'ports'
    ports:
      - '5433:5432'
    # Ephemeral storage for clean state
    tmpfs:
      - /var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d db_lumbung_mesari_test']
      interval: 5s
      timeout: 5s
      retries: 10
    profiles: ['test']

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USER: admin
      ADMINER_DEFAULT_PASSWORD: admin123
      ADMINER_DEFAULT_DB: db_lumbung_mesari
    depends_on:
      - postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI
    volumes:
      - mailpit_data:/data
    environment:
      MP_DATABASE: /data/mailpit.db

volumes:
  postgres_data:
    driver: local
  mailpit_data:
    driver: local
